package assignment2.util;

public enum APIMethod {
    ATTACKER_QUERY_STATE,
    ATTACKER_SET_TARGET,
    ATTACKER_START_SYNC,
    ATTACKER_SYNC_DELTA,
    ATTACKER_SYNC_CYCLE,
    ATTACKER_STOP_SYNC,
    ATTACKER_START_ATTACK,
    ATTACKER_STOP_ATTACK,
   
    COORDINATOR_COMMAND_OK,
    COORDINATOR_COMMAND_FAIL, 
}
